# Semaine 1 : NumPy

## Objectif : comprendre les bases de NumPy

## C'est quoi NumPy ?

NumPy est une bibliothèque Python pour faire des calculs rapides sur des tableaux de nombres (les *arrays*). Pour les calculs, un array NumPy est plus rapide et plus pratique qu'une liste Python.

In [1]:
import numpy as np
print(np.__version__)

2.4.4


## 1. Créer des arrays

In [2]:
# Créons un array basique avec NumPy
array = np.array([0, 4, 2, 3, 1])
print(array)

[0 4 2 3 1]


In [3]:
# On peut aussi transformer une liste Python en array NumPy
liste = [1, 2, 3, 4]
array1 = np.array(liste)
print(array1)
print(type(array1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
# Les arrays multidimensionnels
# 2 dimensions
array2 = np.array([[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]])
print(array2)
print(array2.ndim)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2


In [5]:
# 3 dimensions
array3 = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]],
                   [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
                   [[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
print(array3)
print(array3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [6]:
# np.arange crée un array de nombres qu'on peut ensuite reshape : np.arange(start, stop, step)
o = np.arange(12).reshape(3, 4)  # ici on reshape en 3 lignes et 4 colonnes
o

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2. Les méthodes d'array

In [7]:
# shape permet de connaître la forme (les dimensions) des arrays
print("array1:", array1.shape)
print("array2:", array2.shape)
print("array3:", array3.shape)

array1: (4,)
array2: (3, 3)
array3: (3, 3, 3)


In [8]:
# Calculer la moyenne
print("array1:", array1.mean())
print("array2:", array2.mean())
print("array3:", array3.mean())

array1: 2.5
array2: 4.0
array3: 2.0


In [9]:
# Calculer le maximum (ou le minimum)
print("Max array2:", array2.max())
print("Min array3:", array3.min())

Max array2: 8
Min array3: 1


In [10]:
# Accéder à l'indice de l'élément minimum (ou maximum)
print(array1.argmin())
print(array1.argmax())

0
3


In [11]:
# Ordonner par ordre croissant
print(array)
array.sort()
print(array)

[0 4 2 3 1]
[0 1 2 3 4]


In [12]:
# Ordonner par ordre décroissant
array[::-1]

array([4, 3, 2, 1, 0])

## 3. Indexation et slicing

In [13]:
# Indexation
a = np.array([10, 20, 30, 40, 50, 60])

print(a[0])
print(a[-1])
print(a[-2])

10
60
50


In [14]:
# Slicing
print(a[0:3])
print(a[3:5])
print(a[:6])
print(a[2:])
print(a[::2])
print(a[::-1])

[10 20 30]
[40 50]
[10 20 30 40 50 60]
[30 40 50 60]
[10 30 50]
[60 50 40 30 20 10]


In [15]:
# Matrice à plusieurs dimensions
m = np.arange(12).reshape(3, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
m[1, 2]  # ligne 1, colonne 2 (en Python, le début c'est 0)

np.int64(6)

In [17]:
print('1:', m[0])         # ligne entière
print('2:', m[:, 1])      # colonne entière
print('3:', m[0:2, 1:3])  # sous-matrice
# Avant la virgule, 0:2 prend les lignes 0 et 1 (le 2 est exclu).
# Après la virgule, 1:3 prend les colonnes 1 et 2 (le 3 est exclu).

1: [0 1 2 3]
2: [1 5 9]
3: [[1 2]
 [5 6]]


### Petite info : un slice est une vue, pas une copie

In [18]:
array6 = np.array([1, 2, 3, 4, 5])
print(array6)

[1 2 3 4 5]


In [19]:
B = array6[0:3]
B

array([1, 2, 3])

In [20]:
B[0] = 19
print(B)
print(array6)

[19  2  3]
[19  2  3  4  5]


Ça a directement changé `array6` : un slice est une **vue** qui partage la mémoire avec l'original. C'est là qu'intervient `.copy()`.

In [21]:
C = array6[0:3].copy()
C[0] = 9
print(C)
print(array6)

[9 2 3]
[19  2  3  4  5]


## 4. Masque booléen

In [22]:
z = np.array([12, 13, 4, 9, 5, 44, 1, 3])
print(z > 10)
z[z > 10]

[ True  True False False False  True False False]


array([12, 13, 44])

In [23]:
z[z < 6] = 0
z

array([12, 13,  0,  9,  0, 44,  0,  0])

## Exercice de fin : températures de 4 villes sur 7 jours

In [24]:
temp = np.array([
    [31, 33, 32, 30, 34, 35, 33],   # Abidjan
    [28, 29, 27, 30, 31, 29, 28],   # Bouaké
    [36, 38, 37, 39, 40, 38, 37],   # Korhogo
    [30, 31, 30, 32, 33, 32, 31],   # San-Pédro
])

Chaque ligne est une ville, chaque colonne est un jour (jour 1 à jour 7).

À faire, une ligne de code par question :

1. Affiche les températures de Korhogo.
2. Affiche les températures du jour 3 pour toutes les villes.
3. Affiche Abidjan et Bouaké pour les jours 2 à 5.
4. Affiche les 3 derniers jours pour toutes les villes.
5. Affiche une colonne sur deux (jours 1, 3, 5, 7) pour toutes les villes.
6. Affiche toutes les températures supérieures à 35.
7. Compte combien de valeurs sont supérieures ou égales à 33.
8. Crée `temp_plafonnee`, une copie où toutes les valeurs supérieures à 35 sont remplacées par 35. Vérifie ensuite que `temp` n'a pas changé.

In [25]:
# 1. Affiche les températures de Korhogo
temp[2]

array([36, 38, 37, 39, 40, 38, 37])

In [26]:
# 2. Affiche les températures du jour 3 pour toutes les villes
temp[:, 2]

array([32, 27, 37, 30])

In [27]:
# 3. Affiche Abidjan et Bouaké pour les jours 2 à 5
temp[0:2, 1:5]

array([[33, 32, 30, 34],
       [29, 27, 30, 31]])

In [28]:
# 4. Affiche les 3 derniers jours pour toutes les villes
temp[0:4, 4:7]

array([[34, 35, 33],
       [31, 29, 28],
       [40, 38, 37],
       [33, 32, 31]])

In [29]:
# 5. Affiche une colonne sur deux (jours 1, 3, 5, 7) pour toutes les villes
temp[0:4, 0:7:2]

array([[31, 32, 34, 33],
       [28, 27, 31, 28],
       [36, 37, 40, 37],
       [30, 30, 33, 31]])

In [30]:
# 6. Affiche toutes les températures supérieures à 35
temp[temp > 35]

array([36, 38, 37, 39, 40, 38, 37])

In [31]:
# 7. Compte combien de valeurs sont supérieures ou égales à 33
(temp >= 33).sum()

np.int64(12)

In [32]:
# 8. Crée temp_plafonnee, une copie où les valeurs supérieures à 35 sont remplacées par 35
temp_plafonnee = temp.copy()
temp_plafonnee[temp_plafonnee > 35] = 35
print('temp_plafonnee:')
print(temp_plafonnee)
print('temp (inchangé) :')
print(temp)

temp_plafonnee:
[[31 33 32 30 34 35 33]
 [28 29 27 30 31 29 28]
 [35 35 35 35 35 35 35]
 [30 31 30 32 33 32 31]]
temp (inchangé) :
[[31 33 32 30 34 35 33]
 [28 29 27 30 31 29 28]
 [36 38 37 39 40 38 37]
 [30 31 30 32 33 32 31]]


---
## Bilan : mes erreurs et ce que j'aurais pu faire plus vite

### Mes erreurs
- **Trop d'indices** : j'ai essayé `temp[0:4, 0:7, 2]` pour prendre une colonne sur deux. Résultat : `IndexError`, car `temp` n'a que 2 dimensions. Le pas se met dans le slice : `0:7:2`.
- **Faute de frappe** : `np.arrange` au lieu de `np.arange`.
- **Un doute à retenir** : dans `m[0:2, 1:3]`, avant la virgule ce sont les **lignes**, après la virgule ce sont les **colonnes**.

### Ce que j'aurais pu faire plus vite
| Question | Ce que j'ai écrit | Version plus courte |
|---|---|---|
| 4. Les 3 derniers jours | `temp[0:4, 4:7]` | `temp[:, -3:]` |
| 5. Une colonne sur deux | `temp[0:4, 0:7:2]` | `temp[:, ::2]` |

Le `:` seul veut dire « tout ». Avec `-3:`, le code marche même si le nombre de jours change.

### Bonnes pratiques à adopter
- Donner des noms de variables explicites (`temperatures`, `notes`) plutôt que `array`, `array1`, `array2`.
- `array.sort()` modifie l'array sur place. Pour garder l'original, utiliser `np.sort(array)`.


## Merci 